name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Permet de lancer manuellement comme dans GitLab
    inputs:
      environment:
        description: "Nom de l'environnement (ex: dev, staging, prod)"
        required: false
        default: "dev"
      sub_id:
        description: "Subscription ID Azure"
        required: true
        type: string

env:
  TF_VAR_project_env: dev
  TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  terraform-fmt:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.5.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform version
        run: terraform -version

      - name: Terraform fmt check
        run: terraform fmt -check

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.5.0
    needs: terraform-fmt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        run: terraform -version

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out plan.tfplan

      - name: Save plan as artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/plan.tfplan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    env:
      TF_VAR_subscription_id: ${{ github.event.inputs.sub_id || secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_project_env: ${{ github.event.inputs.environment || env.TF_VAR_project_env }}
    container:
      image: hashicorp/terraform:1.5.0
    needs: terraform-plan
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: terraform

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve plan.tfplan
